project_name: ogc

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd
    id: "ogc"
    binary: ogc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    goarm64:
      - v9.0
    ignore:
      - goos: linux
        goarch: arm
        goarm: 7
      - goamd64: v4

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    builds:
      - ogc
    files:
      - LICENSE
      - README.md

dockers:
  - use: buildx
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    image_templates:
    - "{{ .Env.IMAGE_REPOSITORY }}:{{.Tag}}-amd64"
    - "{{ if not .Prerelease }}{{ .Env.IMAGE_REPOSITORY }}:v{{ .Major }}-amd64{{ end }}"
    - "{{ if not .Prerelease }}{{ .Env.IMAGE_REPOSITORY }}:v{{ .Major }}.{{ .Minor }}-amd64{{ end }}"
    - "{{ if not .Prerelease }}{{ .Env.IMAGE_REPOSITORY }}:latest-amd64{{ end }}"
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.label-schema.schema-version=1.0
      - --label=org.label-schema.version={{ .Version }}
      - --label=org.label-schema.name={{ .ProjectName }}
      - --label=org.label-schema.build-date={{ .Date }}
      - --build-arg=GOOS=linux
      - --build-arg=GOARCH=amd64

  #- use: buildx
  #  dockerfile: Dockerfile
  #  goos: linux
  #  goarch: arm64
  #  image_templates:
  #  - "{{ .Env.IMAGE_REPOSITORY }}:{{.Tag}}-arm64"
  #  - "{{ if not .Prerelease }}{{ .Env.IMAGE_REPOSITORY }}:v{{ .Major }}-arm64{{ end }}"
  #  - "{{ if not .Prerelease }}{{ .Env.IMAGE_REPOSITORY }}:v{{ .Major }}.{{ .Minor }}-arm64{{ end }}"
  #  - "{{ if not .Prerelease }}{{ .Env.IMAGE_REPOSITORY }}:latest-arm64{{ end }}"
  #  build_flag_templates:
  #    - --platform=linux/arm64
  #    - --label=org.opencontainers.image.created={{ .Date }}
  #    - --label=org.opencontainers.image.title={{ .ProjectName }}
  #    - --label=org.opencontainers.image.revision={{ .FullCommit }}
  #    - --label=org.opencontainers.image.version={{ .Version }}
  #    - --label=org.label-schema.schema-version=1.0
  #    - --label=org.label-schema.version={{ .Version }}
  #    - --label=org.label-schema.name={{ .ProjectName }}
  #    - --label=org.label-schema.build-date={{ .Date }}
  #    - --build-arg=GOOS=linux
  #    - --build-arg=GOARCH=arm64

  #- use: buildx
  #  dockerfile: Dockerfile
  #  goos: linux
  #  goarch: s390x
  #  image_templates:
  #  - "{{ .Env.IMAGE_REPOSITORY }}:{{.Tag}}-s390x"
  #  - "{{ if not .Prerelease }}{{ .Env.IMAGE_REPOSITORY }}:v{{ .Major }}-s390x{{ end }}"
  #  - "{{ if not .Prerelease }}{{ .Env.IMAGE_REPOSITORY }}:v{{ .Major }}.{{ .Minor }}-s390x{{ end }}"
  #  - "{{ if not .Prerelease }}{{ .Env.IMAGE_REPOSITORY }}:latest-s390x{{ end }}"
  #  build_flag_templates:
  #    - --platform=linux/s390x
  #    - --label=org.opencontainers.image.created={{ .Date }}
  #    - --label=org.opencontainers.image.title={{ .ProjectName }}
  #    - --label=org.opencontainers.image.revision={{ .FullCommit }}
  #    - --label=org.opencontainers.image.version={{ .Version }}
  #    - --label=org.label-schema.schema-version=1.0
  #    - --label=org.label-schema.version={{ .Version }}
  #    - --label=org.label-schema.name={{ .ProjectName }}
  #    - --label=org.label-schema.build-date={{ .Date }}
  #    - --build-arg=GOOS=linux
  #    - --build-arg=GOARCH=s390x

  #- use: buildx
  #  dockerfile: Dockerfile
  #  goos: linux
  #  goarch: ppc64le
  #  image_templates:
  #  - "{{ .Env.IMAGE_REPOSITORY }}:{{.Tag}}-ppc64le"
  #  - "{{ if not .Prerelease }}{{ .Env.IMAGE_REPOSITORY }}:v{{ .Major }}-ppc64le{{ end }}"
  #  - "{{ if not .Prerelease }}{{ .Env.IMAGE_REPOSITORY }}:v{{ .Major }}.{{ .Minor }}-ppc64le{{ end }}"
  #  - "{{ if not .Prerelease }}{{ .Env.IMAGE_REPOSITORY }}:latest-ppc64le{{ end }}"
  #  build_flag_templates:
  #    - --platform=linux/ppc64le
  #    - --label=org.opencontainers.image.created={{ .Date }}
  #    - --label=org.opencontainers.image.title={{ .ProjectName }}
  #    - --label=org.opencontainers.image.revision={{ .FullCommit }}
  #    - --label=org.opencontainers.image.version={{ .Version }}
  #    - --label=org.label-schema.schema-version=1.0
  #    - --label=org.label-schema.version={{ .Version }}
  #    - --label=org.label-schema.name={{ .ProjectName }}
  #    - --label=org.label-schema.build-date={{ .Date }}
  #    - --build-arg=GOOS=linux
  #    - --build-arg=GOARCH=ppc64le

docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: "{{ .Env.IMAGE_REPOSITORY }}:{{.Tag}}"
    skip_push: false
    image_templates:
      - "{{ .Env.IMAGE_REPOSITORY }}:{{.Tag}}-amd64"
      #- "{{ .Env.IMAGE_REPOSITORY }}:{{.Tag}}-arm64"
      #- "{{ .Env.IMAGE_REPOSITORY }}:{{.Tag}}-s390x"
      #- "{{ .Env.IMAGE_REPOSITORY }}:{{.Tag}}-ppc64le"

  - name_template: "{{ .Env.IMAGE_REPOSITORY }}:v{{ .Major }}"
    skip_push: auto
    image_templates:
      - "{{ .Env.IMAGE_REPOSITORY }}:v{{ .Major }}-amd64"
      #- "{{ .Env.IMAGE_REPOSITORY }}:v{{ .Major }}-arm64"
      #- "{{ .Env.IMAGE_REPOSITORY }}:v{{ .Major }}-s390x"
      #- "{{ .Env.IMAGE_REPOSITORY }}:v{{ .Major }}-ppc64le"

  - name_template: "{{ .Env.IMAGE_REPOSITORY }}:v{{ .Major }}.{{ .Minor }}"
    skip_push: auto
    image_templates:
      - "{{ .Env.IMAGE_REPOSITORY }}:v{{ .Major }}.{{ .Minor }}-amd64"
      #- "{{ .Env.IMAGE_REPOSITORY }}:v{{ .Major }}.{{ .Minor }}-arm64"
      #- "{{ .Env.IMAGE_REPOSITORY }}:v{{ .Major }}.{{ .Minor }}-s390x"
      #- "{{ .Env.IMAGE_REPOSITORY }}:v{{ .Major }}.{{ .Minor }}-ppc64le"

  - name_template: "{{ .Env.IMAGE_REPOSITORY }}:latest"
    skip_push: auto
    image_templates:
      - "{{ .Env.IMAGE_REPOSITORY }}:latest-amd64"
      #- "{{ .Env.IMAGE_REPOSITORY }}:latest-arm64"
      #- "{{ .Env.IMAGE_REPOSITORY }}:latest-s390x"
      #- "{{ .Env.IMAGE_REPOSITORY }}:latest-ppc64le"

checksum:
  name_template: 'checksums.txt'

release:
  draft: false
  discussion_category_name: General
  prerelease: auto
  mode: append
  header: |
    ## Release {{ .Version }} [{{ .Date }}]
  footer: |
    ## Docker Images

    - {{ .Env.IMAGE_REPOSITORY }}:{{.Tag}}
    {{- if not .Prerelease }}
    - {{ .Env.IMAGE_REPOSITORY }}:v{{ .Major }}
    - {{ .Env.IMAGE_REPOSITORY }}:v{{ .Major }}.{{ .Minor }}
    - {{ .Env.IMAGE_REPOSITORY }}:latest
    {{- end }}

  extra_files:
    - glob: LICENSE
    - glob: README.md

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Enhancements"
      regexp: "^.*enhancement[(\\w)]*:+.*$"
      order: 2
    - title: "Documentation changes"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 3
    - title: "Code refactoring"
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 4
    - title: Dependency updates
      regexp: "^build[(deps)]: bump +.*$"
      order: 998
    - title: Others
      order: 999
  filters:
    exclude:
      - "^test:"
      - "^github:"
      - "^ci:"
      - "^cd:"
      - "^ci/cd:"
      - "^example:"
      - "^gomod:"
      - "^git:"
      - "^goreleaser:"
      - "^Merge branch"
      - "WIP"
